# Generated by Django 3.1.6 on 2021-10-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccount',
            fields=[
                ('u_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_displayname', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
