# Generated by Django 3.1.6 on 2021-10-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0006_albummodel_image_investiage_language_photomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='investiage',
            new_name='investigate',
        ),
    ]
